import sys

mouse_fasta = "mm10.fa"  
human_fasta = "hmm10.fa" 
chimp_fasta = "cmm10.fa"
chromosome = "chr1"  
start = 89713752  
end = 89714911  

human_sequence = "CCAGCATACAGTAGCTTCATTGGCTTTTTTTCTGCCCATATTCAAAATTCCTTTGATTAGCATTTGGTTCTGGTTGGGACTTAATAATGCTAGCCAGACCTAATGTGAACCATACATCTCGTCGGCATTACTCATCGTCAACATGGGTTTTTAAAAGGGAAGGAGAGAAACACAACAAACTTTTTATTTCTTTCCCTGTCATTGTTCTTGGTCTTGTTATTCAGTGGACGCTGTATTAAATTGGATTCTGTGTCCATCATTATTAAAATGTGAAGTGTGTCGGTCACAAAGCATACATTTCGGGGCAGTTAGCTGAATAATTCTTTTCTTTATTATCCCAAATTACTGCTGAGCTCTGGAGAGGGGAGCAGTTTAGCCAATTATTGCCATTTGAGCTGGATTTGTGGGTGATTAGCTCCTGGCCGAATCCAGTCCCGGCCGGCGCTTTGAAGCCTGTGCTGTGCGATTTTCTCAGCAGTGAGGTAGGAATAGACGCGGCTAATGACAGGAAGGTCGCGCGGGTGAGCTGACCTGTGTGTGGCGCAGCCTTGGGTTCCGCAAATAGGGCACCCACAGTAACACGTGTGGCGCCGACCCCGCCGTGCGCAATCGGGGCTTTATACGATTGCTGGAGATGCTGACAGCTCAATTAAAGTGTAACCCTTTGTGCCCTGCAACCTGGCACAACGACAGAAATATTACTCGCCGGAAAGGGGAGGGGGTCTTTGGGGAGCTGGTTAAAGATCCAGAATCGGCCCCTCGCCCCTTTGCCCCTCCCCCAACTCCCTCCACTGTACAGAAGGAGCTGCAGAAAAGCCTCCATTTGTAAAATAATAGGTGCTCTGGAGGAGGGGCAGGGCGGGAAATATTACTATTTTAAAAAGCTCAGTTAAGGGGGGATTCCTGCTGTTCCTATGGAAACACTTTAAACTAGAGAGAAAGTTAAAAAGATTTAGTAGCGGCAGAGCTTGTGTCTGCTGGTCACATTTTCTAGTCATCTCCTTTTACCAAAATTTACCTCCCAGCATCGTGGATGTGAATTTGCCAGAAGTTTTCCGTTTGTGGAGGACTGGGGAAAGCCAGTTAATTGGGATGTGTTTTTGCACACAACGAATGATTTCTATGTTATCGATTTACTTCTTTCACTTAACGGCATTTTCTGCAGCTTGAATGAAAGCTGTCTCGATCCATGTATGTCTGTGTATCTGCGGTCTGGTCATTTTTGCCACACTTGAT"
chimp_sequence = "CCAGCATATAGTAGCTTCATTGGCTTTTTTTCTGCCCATATTCAAAATTCCTTTGATTAGCATTTGGTTCTGGTTGGGACTTAATAATGCTAGCCAGACCTAATGTGAACCATACATCTCGTCGGCATTACTCATCGTCAACATGGGTTTTTAAAAGGGAAGGAGAGAAACACAACAAACTTTTTATTTCTTTCCCTGTCATTGTTCTTGGTCTTGTTATTCAGTGGACGCTGTATTAAATTGGATTCTGTGTCCATCATTATTAAAATGTGAAGTGTGTCGGTCACAAAGCATACATTTCGGGGCAGTTAGCTGAATAATTCTTTTCTTTATTATCCCAAATTACTGCTGAGCTCTGGAGAGGGGAGCAGTTTAGCCAATTATTGCCATTTGAGCTGGATTTGTGGGTGATTAGCTCCTGGCCGAATCCAGTCCCGGCCGGCGCTTTGAAGCCTGTGCTGTGTGATTTTCTCAGCAGTGAGGTAGGAATAGACGCGGCTAATGACAGGAAGGTCGCGCGGGTGAGCTGACCTGTGTGTGGCACAGGCTTGGGTTTCGCAAATAGGGCATCCACAATAACAAGTGTGTCACTAACCCCGCCGTGCATAATCGGGGCTTTATAGGATTGCTGGAGATGCTGACAGCTCAATTAAAGTGTAACCCTTTGTACCCTGCAACCTGGCACAACGACAGAAATATTACTCGCCAGAAAGGGGAGGGGGTCTTTGGGGAGCTGGTTAAAGATCCAGAATCGGCCCCTCGCCCCTTTGCCCCTCCCCCAACTCCCTCCACTGTACAGAAGGAGCCGCAGAAAAGCCTCCATTTGTAAAATAATAGGTGCTCTGGAGGAGGGGCAGGGCGGGAATATTACTATTTTAAAAAGCTCAGTTAAGGGGGGATTCCTGCTGTTCCTATGGAAACACTTTAAACTAGATAGAAAGTTAAAAAGATTTAGTAGCGGCAGAGCTTGTGTCTGCTGGTCACATTTTCTAGTCATCTCCTTTTACCAAAATTTACCTCCCAGCATCGTGGATGTGAATTTGCCAGAAGTTTTCCGTTTGTGGAGGACTGGGGAAAGCCAGTTAATTGGGATGTGTTTTTGCACACAACGAATGATTTCTATGTTATCGATTTACTTCTTTCACTTAACGGCATTTTCTGCAGCTTGAATGAAAGCTGTCTTGATCCATGTATGTCTGTGTATCTGTGGTCTGGTCATTTTTGCCACACTTGAT"

with open(mouse_fasta, "r") as f:
    lines = f.readlines()

output_lines = []
current_chromosome = None
current_sequence = []
replace_mode = False

for line in lines:
    if line.startswith(">"):  
        if current_chromosome == chromosome:
            full_sequence = "".join(current_sequence)
            before = full_sequence[: start - 1]
            after = full_sequence[end:]
            modified_sequence = before + human_sequence + after
            output_lines.append(modified_sequence + "\n")
        
        current_chromosome = line.strip().split()[0][1:]  
        output_lines.append(line.strip() + "\n")

        current_sequence = []
        replace_mode = current_chromosome == chromosome
    elif replace_mode:
        current_sequence.append(line.strip())
    else:
        output_lines.append(line.strip() + "\n")

if current_chromosome == chromosome:
    full_sequence = "".join(current_sequence)
    before = full_sequence[: start - 1]
    after = full_sequence[end:]
    modified_sequence = before + human_sequence + after
    output_lines.append(modified_sequence + "\n")

with open(human_fasta, "w") as f:
    f.writelines(output_lines)

for line in lines:
    if line.startswith(">"):  
        if current_chromosome == chromosome:
            full_sequence = "".join(current_sequence)
            before = full_sequence[: start - 1]
            after = full_sequence[end:]
            modified_sequence = before + chimp_sequence + after
            output_lines.append(modified_sequence + "\n")
        
        current_chromosome = line.strip().split()[0][1:]  
        output_lines.append(line.strip() + "\n")

        current_sequence = []
        replace_mode = current_chromosome == chromosome
    elif replace_mode:
        current_sequence.append(line.strip())
    else:
        output_lines.append(line.strip() + "\n")

if current_chromosome == chromosome:
    full_sequence = "".join(current_sequence)
    before = full_sequence[: start - 1]
    after = full_sequence[end:]
    modified_sequence = before + chimp_sequence + after
    output_lines.append(modified_sequence + "\n")

with open(chimp_fasta, "w") as f:
    f.writelines(output_lines)
